name: env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - brotlipy=0.7.0
  - reaktoro=1.*
  - scipy
  - numpy
  - pandas
  - pip
  - pip:
    - streamlit==1.11.0
#     - bokeh
#     - pandas
#     - matplotlib
#     - IPython
#     - voila
